include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/src/core/localization/generated/**"
    - "**/*.*.dart"

dart_code_metrics:
  extends:
    - recommended

formatter:
  page_width: 80