name: it_interview_monster
description: "IT interview monster"
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3 <4.0.0"

workspace:
  - packages/logger

dependencies:
  async: 2.12.0
  clock: 1.1.2
  collection: 1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.0
  flutter_lints: 5.0.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  logger:
    path: packages/logger
  meta: 1.16.0
  package_info_plus: 8.3.0
  path: 1.9.1
  path_provider: 2.1.5
  sentry_flutter: 8.13.3
  shared_preferences: 2.5.3
  stack_trace: 1.12.1

dev_dependencies:
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  flutter_launcher_icons: 0.14.3
  flutter_native_splash: 2.4.6
  flutter_test:
    sdk: flutter
  mockito: 5.4.6
  sizzle_lints: 2.1.7

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
