name: api
description: "Generated API code from OpenAPI specification"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  retrofit: ^4.7.3
  rest_client:
    path: ../rest_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.3
  json_serializable: ^6.8.0
  freezed: ^3.2.3
  retrofit_generator: ^10.0.6
  swagger_parser: ^1.32.1
