name: uikit
description: "UI kit"
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
